pipeline {
    agent { label 'jnlp-slave' }
    environment {
        JAVA_HOME = "/data/jdk1.8.0_101"
    }
    
	stages {
		stage("Description") {
            steps {
                script {
				   wrap([$class: 'BuildUser']) {
					   currentBuild.displayName = "#$BUILD_NUMBER $gitlabTargetBranch $gitlabUserName"
                   }
                    
                } 
            }
        }

		stage('Clone') {
			steps {
				script{
					git([url: env.gitlabSourceRepoSshUrl, branch: env.gitlabTargetBranch])					
				}					
			}
		}

		stage('Build') {
			steps {
				sh '''
					/usr/bin/python3 /data/scripts/jenkins.py $gitlabSourceRepoSshUrl $gitlabTargetBranch
				'''
			}
		}

		stage('ImagePush') {
			steps {
				sh '''
					/usr/bin/python3 /data/scripts/imagePush.py $gitlabSourceRepoSshUrl $gitlabTargetBranch 
				'''
			}
		}
		
		stage('SonarScan') {
			steps {
				sh '''
					/usr/bin/python3 /data/scripts/sonarScan.py $gitlabSourceRepoSshUrl $gitlabTargetBranch $gitlabUserName
				'''
			}
		}

		stage('ConsoleOutput') {
			steps {
				sh '''
					/usr/bin/python3 /data/scripts/consoleOutput.py $gitlabSourceRepoSshUrl $gitlabTargetBranch
				'''
			}
		}
		

	}
}
